services:
  postgres:
    container_name: postgres
    image: postgres:15.1-alpine
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - sales-force-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    container_name: api
    build:
      context: .
    restart: always
    environment:
      PORT: ${PORT}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${DB_PORT}/${POSTGRES_DB}?schema=public
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    networks:
      - sales-force-network

networks:
  sales-force-network:
    driver: bridge

volumes:
  postgres-data:
